# Generated by Django 4.2.1 on 2023-05-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='equipo_id',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='tecnicos',
            old_name='equipo_id',
            new_name='equipo',
        ),
    ]
