# Generated by Django 4.2.1 on 2023-06-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0002_rename_equipo_id_jugadores_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnicos',
            name='nacionalidad',
        ),
    ]
