# Generated by Django 4.2.1 on 2023-07-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0003_remove_tecnicos_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='escudo',
            field=models.ImageField(null=True, upload_to='imagenes_equipos'),
        ),
    ]
