# Generated by Django 4.2.1 on 2023-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0004_equipos_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='escudo',
            field=models.ImageField(null=True, upload_to='equipos_escudos'),
        ),
    ]
