# Generated by Django 4.2.1 on 2023-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0005_alter_equipos_escudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='edad',
            new_name='nacimiento',
        ),
    ]
